AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  cloudformation-apigateway-stepfunctions-lambda-app

  Sample SAM Template for sam-app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20

Resources:

  LambdaDynamoDBWriteRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: "sts:AssumeRole"
      Path: "/"
      Policies:
        - PolicyName: DynamoDBPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "dynamodb:PutItem"
                Resource: "*"

  StatesExecutionRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - !Sub states.${AWS::Region}.amazonaws.com
            Action: "sts:AssumeRole"
      Path: "/"
      Policies:
        - PolicyName: StatesExecutionPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "lambda:InvokeFunction"
                Resource: "*"
        - PolicyName: DynamoDBPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "dynamodb:PutItem"
                Resource: "*"

  BusinessValidationFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: BusinessValidationFunction
      Handler: functions.BusinessValidationFunction::handleRequest
      Runtime: java8

  EnrichmentFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: EnrichmentFunction
      Handler: functions.EnrichmentFunction::handleRequest
      Runtime: java8

  StoreFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: StoreFunction
      Handler: app.lambda_handler
      Runtime: python3.7
      # Policies: LambdaDynamoDBWriteRole
      Role: !GetAtt [ LambdaDynamoDBWriteRole, Arn]

  ErrorFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ErrorFunction
      Handler: functions.ErrorFunction::handleRequest
      Runtime: java8

  UsedCarStateMachine:
    Type: "AWS::StepFunctions::StateMachine"
    Properties:
      DefinitionString:
        !Sub
        - |-
          {
            "Comment": "Used Car dataflow",
            "StartAt": "BusinessValidations",
            "States": {
                "BusinessValidations": {
                    "Catch": [
                        {
                            "ErrorEquals": [
                                "States.ALL"
                            ],
                            "Next": "ErrorHandler"
                        }
                    ],
                    "Next": "ValidationSuccess",
                    "Resource": "${lambdaBusinessValidation}",
                    "Type": "Task"
                },
                "ValidationSuccess": {
                    "Type": "Choice",
                    "Choices":[
                      {
                        "Variable":"$.status",
                        "StringEquals":"Valid",
                        "Next":"Enrichment"
                      }
                    ],
                    "Default": "StoreData"
                },
                "Enrichment": {
                    "Catch": [
                        {
                            "ErrorEquals": [
                                "States.ALL"
                            ],
                            "Next": "ErrorHandler"
                        }
                    ],
                    "Next": "StoreData",
                    "Resource": "${lambdaEnrichment}",
                    "Type": "Task"
                },
                "ErrorHandler": {
                    "End": true,
                    "Resource": "${lambdaError}",
                    "Type": "Task"
                },
                "StoreData": {
                    "Catch": [
                        {
                            "ErrorEquals": [
                                "States.ALL"
                            ],
                            "Next": "ErrorHandler"
                        }
                    ],
                    "End": true,
                    "Resource": "${lambdaStore}",
                    "Type": "Task"
                }
            }
          }
        - {lambdaStore: !GetAtt [ StoreFunction, Arn ],
         lambdaBusinessValidation: !GetAtt [ BusinessValidationFunction, Arn ],
         lambdaEnrichment: !GetAtt [ EnrichmentFunction, Arn ],
         lambdaError: !GetAtt [ ErrorFunction, Arn ]}
      RoleArn: !GetAtt [ StatesExecutionRole, Arn]

  PublicApi:
    Type: AWS::Serverless::Api
    Properties:
        StageName: prod
        DefinitionBody:
            swagger: 2.0
            info:
              title:
                Ref: AWS::StackName
            paths:
              /sfnonly: # api gateway invokes step function asynchronously
                get:
                  produces:
                  - "application/json"
                  responses:
                    "200":
                      description: "200 response"
                      schema:
                        $ref: "#/definitions/Empty"
                      headers:
                         Access-Control-Allow-Headers:
                          type: "string"

                  security: []
                  x-amazon-apigateway-integration:
                    responses:
                      default:
                        statusCode: "200"
                        headers:
                         Access-Control-Allow-Headers:
                          type: "'*'"
                    passthroughBehavior: "when_no_match"
                    httpMethod: "POST"
                    type: "aws"
                    credentials: !GetAtt APIGatewayRole.Arn
                    uri: "arn:aws:apigateway:eu-west-1:states:action/StartExecution"
                    requestTemplates:
                      application/json:
                        !Sub
                          |-
                            {
                              "input": "$util.escapeJavaScript($input.json('$'))",
                              "stateMachineArn": "${UsedCarStateMachine}"
                            }

              # /lambda2sfn: # api gateway invokes lambda synchronously, which in turn invokes the stepfunction and waits for its final result
              #   get:
              #     produces:
              #     - "application/json"
              #     responses:
              #       "200":
              #         description: "200 response"
              #         schema:
              #           $ref: "#/definitions/Empty"
              #         headers:
              #            Access-Control-Allow-Headers:
              #             type: "string"

              #     security: []
              #     x-amazon-apigateway-integration:
              #       responses:
              #         default:
              #           statusCode: "200"
              #           headers:
              #            Access-Control-Allow-Headers:
              #             type: "'*'"
              #       httpMethod: POST
              #       type: aws_proxy
              #       uri:
              #         Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${HelloWorldExecutor.Arn}/invocations

            definitions:
              Empty:
                type: "object"
                title: "Empty Schema"

  APIGatewayRole: 
    Type: AWS::IAM::Role
    Properties: 
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - Effect: Allow
            Principal: 
              Service: 
                - "apigateway.amazonaws.com"
            Action: "sts:AssumeRole"
      Path: "/"
      ManagedPolicyArns: 
        - "arn:aws:iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs"
        - "arn:aws:iam::aws:policy/AWSStepFunctionsFullAccess"

  UsedCarDB:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        -
         AttributeName: "contextId"
         AttributeType: "S"
      KeySchema:
        -
          AttributeName: "contextId"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: "1"
        WriteCapacityUnits: "1"
      TableName: "vehicles"